export default {
  FETCHING: 'FETCHING',
  CANCEL_FETCHING: 'CANCEL_FETCHING',
  SET_SYNC_DATE: 'SET_SYNC_DATE',
  SET_RATIO_CONFIG: 'SET_RATIO_CONFIG',
  SET_USERS_CONFIG: 'SET_USERS_CONFIG',
  SET_EXPENSE_GROUPS: 'SET_EXPENSE_GROUPS',
  CHANGE_EXPENSE_GROUP: 'CHANGE_EXPENSE_GROUP',
  SET_BILLS: 'SET_BILLS',
  CHANGE_BILL: 'CHANGE_BILL'
}